pipeline:
  build:
    image: docker
    commands:
      - docker build --rm -t quay.io/kubermatic/seed-installer-e2e-builder:${DRONE_COMMIT_SHA} ./kubeadm-seed-installer/ -f ./kubeadm-seed-installer/test/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test-openstack:
    group: test
    image: quay.io/kubermatic/seed-installer-e2e-builder:${DRONE_COMMIT_SHA}
    environment:
      - DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    secrets:
      - secret_basepath
      - approle_id
      - secret_id
      - vault_addr
    commands: /test/run-test.sh openstack
  test-aws:
    group: test
    image: quay.io/kubermatic/seed-installer-e2e-builder:${DRONE_COMMIT_SHA}
    secrets:
      - approle_id
      - secret_id
      - vault_addr
    commands:
      - /test/run-test.sh aws
  cleanup:
    image: docker
    commands:
      - docker rmi --force quay.io/kubermatic/seed-installer-e2e-builder:${DRONE_COMMIT_SHA}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ success, failure ]
